#!/usr/bin/env python3
"""tools/phonero-to-js.py — a Phonero commission report → venditus/phonero-grunnlag.js

The report Venditus gets from Phonero ("DanaKopiGrunnlag"): one sheet, one block
per seller (a numbered header row, then one row per customer and product), the
rates on row 4, deductions in AB with the reason in AD.

    python3 tools/phonero-to-js.py "<report.xlsx>"            # real   → venditus/phonero-grunnlag.js (git-ignored)
    python3 tools/phonero-to-js.py "<report.xlsx>" --anon     # public → venditus/phonero-demo.js

The real output holds REAL CUSTOMER NAMES and is listed in .gitignore. It must
never be committed or deployed — the repo is public and main goes straight to
Vercel. --anon writes a copy that is safe to publish: customers become
"Kunde 001…", phone numbers, staff names, initials and ages are removed from the
comments, and the run fails if anything from the original survives. Every
number is unchanged. The page loads the demo first and the real file (when it
exists locally) on top of it.
"""
import json, os, sys, datetime
import openpyxl
from openpyxl.utils import get_column_letter

import re
if len(sys.argv) < 2:
    sys.exit(__doc__)
src = sys.argv[1]
ANON = '--anon' in sys.argv[2:]
out = os.path.join(os.path.dirname(__file__), '..', 'venditus', 'phonero-demo.js' if ANON else 'phonero-grunnlag.js')

wf = openpyxl.load_workbook(src)                  # formulas
wv = openpyxl.load_workbook(src, data_only=True)  # the values Excel last saved
sf, sv = wf.worksheets[0], wv.worksheets[0]

def fill(c):
    f = c.fill
    if not f or f.fill_type != 'solid' or not f.fgColor or f.fgColor.type != 'rgb':
        return None
    rgb = f.fgColor.rgb or ''
    return None if rgb in ('00000000', 'FFFFFFFF') else '#' + rgb[-6:]

def plain(v):
    if isinstance(v, (datetime.date, datetime.datetime)):
        return v.isoformat()[:10]
    return v

cells = {}
last_row = 0
for row in sf.iter_rows():
    for c in row:
        v = sv[c.coordinate].value
        f = c.value if isinstance(c.value, str) and c.value.startswith('=') else None
        fl = fill(c)
        if v is None and f is None and fl is None:
            continue
        cell = {}
        if v is not None: cell['v'] = plain(v)
        if f: cell['f'] = f
        if fl: cell['fill'] = fl
        if c.font and c.font.b: cell['b'] = 1
        cells[c.coordinate] = cell
        if v is not None or f: last_row = max(last_row, c.row)

widths = {k: round(d.width, 1) for k, d in sf.column_dimensions.items() if d.width}

# ── anonymise: customers in B, people and numbers inside the comments ──
real_names = []
if ANON:
    alias, n = {}, 0
    for r in range(1, last_row + 1):
        c = cells.get('B%d' % r)
        if not c or not isinstance(c.get('v'), str) or r <= 5: continue
        name = c['v'].strip()
        if name.lower().startswith('venditus'): continue
        if name not in alias:
            n += 1; alias[name] = 'Kunde %03d' % n
        c['v'] = alias[name]
    real_names = sorted(alias, key=len, reverse=True)
    def clean(t):
        for nm in real_names:                       # a customer named inside a comment
            if len(nm) > 3: t = t.replace(nm, alias[nm])
        t = re.sub(r'(?<!\d)[2-9]\d{7}(?!\d)', '[nummer]', t)     # Norwegian phone numbers
        t = re.sub(r'\(pensjonist på \d+ år\)', '(pensjonist)', t)
        t = re.sub(r'\s*-\s*Rune\b', '', t)                        # a staff member's first name
        t = re.sub(r'\bAKJ\b', '', t)                               # staff initials
        return t
    for a, c in cells.items():
        col = re.match(r'[A-Z]+', a).group(0)
        if col in ('AD', 'AE') and isinstance(c.get('v'), str): c['v'] = clean(c['v'])


data = {
    'source': ('Phonero-rapport (anonymisert)' if ANON else os.path.basename(src)),
    'anon': bool(ANON),
    'sheet': sf.title.strip(),
    'maxRow': last_row,
    'maxCol': sf.max_column,
    'cols': [get_column_letter(i) for i in range(1, sf.max_column + 1)],
    'widths': widths,
    'merged': [str(m) for m in sf.merged_cells.ranges],
    'cells': cells,
}

payload = json.dumps(data, ensure_ascii=False)
if ANON:
    # refuse to write a "safe" file that is not
    leaks = [nm for nm in real_names if len(nm) > 3 and nm in payload]
    leaks += re.findall(r'(?<!\d)[2-9]\d{7}(?!\d)', payload)
    leaks += [w for w in ('Rune', 'AKJ', 'pensjonist på') if w in payload]
    if leaks: sys.exit('anonymisation incomplete, not written: %r' % leaks[:10])

with open(out, 'w', encoding='utf8') as fh:
    if ANON:
        fh.write('/* GENERATED by tools/phonero-to-js.py --anon — anonymised, safe to publish.\n'
                 '   Customers are "Kunde 001…"; phone numbers, staff names and ages removed. Numbers unchanged. */\n')
        fh.write('window.PHONERO_GRUNNLAG = window.PHONERO_GRUNNLAG || ' + payload + ';\n')
    else:
        fh.write('/* GENERATED by tools/phonero-to-js.py — do not edit, do not commit.\n'
                 '   Contains real customer names from ' + data['source'] + '. Listed in .gitignore. */\n')
        fh.write('window.PHONERO_GRUNNLAG = ' + payload + ';\n')

print(os.path.relpath(out, os.path.join(os.path.dirname(__file__), '..')), '—', len(cells), 'cells,', last_row, 'rows, sheet', repr(data['sheet']))
