#!/usr/bin/env python3
"""tools/phonero-to-js.py — a Phonero commission report → venditus/phonero-grunnlag.js

The report Venditus gets from Phonero ("DanaKopiGrunnlag"): one sheet, one block
per seller (a numbered header row, then one row per customer and product), the
rates on row 4, deductions in AB with the reason in AD.

    python3 tools/phonero-to-js.py "<report.xlsx>"

The output holds REAL CUSTOMER NAMES and is listed in .gitignore. It must never
be committed or deployed — the repo is public and main goes straight to Vercel.
Without the file the page simply has no PHONERO-GRUNNLAG sheet.
"""
import json, os, sys, datetime
import openpyxl
from openpyxl.utils import get_column_letter

if len(sys.argv) < 2:
    sys.exit(__doc__)
src = sys.argv[1]
out = os.path.join(os.path.dirname(__file__), '..', 'venditus', 'phonero-grunnlag.js')

wf = openpyxl.load_workbook(src)                  # formulas
wv = openpyxl.load_workbook(src, data_only=True)  # the values Excel last saved
sf, sv = wf.worksheets[0], wv.worksheets[0]

def fill(c):
    f = c.fill
    if not f or f.fill_type != 'solid' or not f.fgColor or f.fgColor.type != 'rgb':
        return None
    rgb = f.fgColor.rgb or ''
    return None if rgb in ('00000000', 'FFFFFFFF') else '#' + rgb[-6:]

def plain(v):
    if isinstance(v, (datetime.date, datetime.datetime)):
        return v.isoformat()[:10]
    return v

cells = {}
last_row = 0
for row in sf.iter_rows():
    for c in row:
        v = sv[c.coordinate].value
        f = c.value if isinstance(c.value, str) and c.value.startswith('=') else None
        fl = fill(c)
        if v is None and f is None and fl is None:
            continue
        cell = {}
        if v is not None: cell['v'] = plain(v)
        if f: cell['f'] = f
        if fl: cell['fill'] = fl
        if c.font and c.font.b: cell['b'] = 1
        cells[c.coordinate] = cell
        if v is not None or f: last_row = max(last_row, c.row)

widths = {k: round(d.width, 1) for k, d in sf.column_dimensions.items() if d.width}

data = {
    'source': os.path.basename(src),
    'sheet': sf.title.strip(),
    'maxRow': last_row,
    'maxCol': sf.max_column,
    'cols': [get_column_letter(i) for i in range(1, sf.max_column + 1)],
    'widths': widths,
    'merged': [str(m) for m in sf.merged_cells.ranges],
    'cells': cells,
}

with open(out, 'w', encoding='utf8') as fh:
    fh.write('/* GENERATED by tools/phonero-to-js.py — do not edit, do not commit.\n'
             '   Contains real customer names from ' + data['source'] + '. Listed in .gitignore. */\n')
    fh.write('window.PHONERO_GRUNNLAG = ' + json.dumps(data, ensure_ascii=False) + ';\n')

print('venditus/phonero-grunnlag.js —', len(cells), 'cells,', last_row, 'rows, sheet', repr(data['sheet']))
