#!/usr/bin/env python3
"""Dump a workbook to venditus/raw.js — cells, formulas and fill colours, nothing interpreted.

The interpretation lives in venditus/parse.js so that this seed path and the
in-browser upload path (SheetJS) share one set of rules. This script only
flattens the file; it makes no decisions about what the sheets mean.

    python3 tools/xlsx-to-raw.py ~/Downloads/Venditus_v2_Mikro_final.xlsx
"""
import json
import sys
from pathlib import Path

import openpyxl

# The workbook encodes provenance in the fill colour, consistently across every
# sheet. Clario reads it back as an edit-permission map: yellow cells are the
# ones a user may type into.
FILL_ROLE = {
    'FFFFF2CC': 'input',     # yellow  — fill in manually
    'FFE2EFDA': 'computed',  # green   — calculated, do not edit
    'FFFCE4D6': 'external',  # orange  — from Tripletex / Phonero
    'FFFFE0E0': 'absence',   # red     — absence-related
    'FF375623': 'key',       # navy    — headline figure
}


def cell_role(cell):
    rgb = getattr(cell.fill.start_color, 'rgb', None)
    if not isinstance(rgb, str):
        return None
    return FILL_ROLE.get(rgb.upper())


def dump(path):
    wb = openpyxl.load_workbook(path, data_only=False)
    sheets = {}

    for ws in wb.worksheets:
        cells = {}
        for row in ws.iter_rows():
            for cell in row:
                if cell.value is None:
                    continue
                entry = {}
                value = cell.value
                if isinstance(value, str) and value.startswith('='):
                    entry['f'] = value
                else:
                    entry['v'] = value.isoformat() if hasattr(value, 'isoformat') else value
                role = cell_role(cell)
                if role:
                    entry['r'] = role
                fmt = cell.number_format
                if fmt and fmt != 'General':
                    entry['z'] = fmt
                cells[cell.coordinate] = entry

        sheets[ws.title] = {
            'name': ws.title,
            'maxRow': ws.max_row,
            'maxCol': ws.max_column,
            'cells': cells,
        }

    return {
        'source': Path(path).name,
        'sheetNames': wb.sheetnames,
        'sheets': sheets,
    }


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)

    src = sys.argv[1]
    raw = dump(src)

    out = Path(__file__).resolve().parent.parent / 'venditus' / 'raw.js'
    payload = json.dumps(raw, ensure_ascii=False, indent=1)
    out.write_text(
        '/* GENERATED by tools/xlsx-to-raw.py — do not edit by hand.\n'
        f'   Source: {raw["source"]}\n'
        '   Regenerate: python3 tools/xlsx-to-raw.py <workbook.xlsx> */\n'
        'window.VENDITUS_RAW = ' + payload + ';\n',
        encoding='utf-8',
    )

    total = sum(len(s['cells']) for s in raw['sheets'].values())
    print(f'{out}  —  {len(raw["sheetNames"])} sheets, {total} cells')
    for name in raw['sheetNames']:
        s = raw['sheets'][name]
        roles = {}
        for c in s['cells'].values():
            if 'r' in c:
                roles[c['r']] = roles.get(c['r'], 0) + 1
        tag = ' '.join(f'{k}:{v}' for k, v in sorted(roles.items()))
        print(f'  {name:<24} {len(s["cells"]):>5} cells   {tag}')


if __name__ == '__main__':
    main()
